import { AiFillStar } from "react-icons/ai";

const data = [
  {
    id: 1,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
,
    img: "https://m.media-amazon.com/images/I/51Y3y0GujlL._AC_UL600_FMwebp_QL65_.jpg",
    title: "Puma BMW ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "140,00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
      },
  {
    id: 2,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/71F-dn0dwNL._UX695_.jpg",
    title: "Puma Pwrframe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },

  {
    id: 3,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/51cSS91ny+L._AC_UL600_FMwebp_QL65_.jpg",
    title: "Nike Mens Precision Vi Running Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },
  

  {
    id:4,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/41+8JvBA9KL._AC_UL600_FMwebp_QL65_.jpg",
    title: "Mens M Air Max Alpha Trainer 5 Running",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Vans",
    color: "white",
    category: "flats",
  },

  {
    id:5,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    title: "Nike Zoom Freak",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },

  {
    id:6,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/712hQWPtDiL._AC_UL600_FMwebp_QL65_.jpg",
    title: "Balenciaga Sheer",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    color: "blue",
    category: "sneakers",
  },
  {
    id:7,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/61DkuWBPIYL._AC_UL600_FMwebp_QL65_.jpg",
    title: "Adidas grand court",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "140,00",
    newPrice: "150",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    id:8,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/713LAFOejcL._AC_UL600_FMwebp_QL65_.jpg",
    title: "Adida Unisex",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "140,00",
    newPrice: "150",
    company: "Puma",
    color: "red",
    category: "sneakers",
  },
  {
    id:9,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/71E209uyVRL._AC_UL600_FMwebp_QL65_.jpg",
    title: "Puma ONE",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "140,00",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },
  {
    id:10,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/51ZIJv27k0L._AC_UL600_FMwebp_QL65_.jpg",
    title: "New Balance",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "140,00",
    newPrice: "150",
    company: "Puma",
    color: "white",
    category: "sneakers",
  },
  {
    id:11,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    title: "Pacer Future Doubleknit",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "140,00",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },

  {
    id:12,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Fusion Evo Golf Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "140,00",
    newPrice: "100",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    id:13,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/313CFnWPpRL._AC_UL600_FMwebp_QL65_.jpg",
    title: "Nike new Skate",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "140,00",
    newPrice: "100",
    company: "Vans",
    color: "red",
    category: "flats",
  },
  {
    id:14,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/511Fg97EIPL._AC_UL600_FMwebp_QL65_.jpg",
    title: "Puma Slides",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "140,00",
    newPrice: "100",
    company: "Vans",
    color: "white",
    category: "sandals",
  },
  {
    id:15,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/71JedyW-pyL._AC_UL600_FMwebp_QL65_.jpg",
    title: "Puma BMW M SPORT",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "140,00",
    newPrice: "100",
    company: "Vans",
    color: "blue",
    category: "sandals",
  },
  {
    id:16,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/51-nmbM-qvL._AC_UL600_FMwebp_QL65_.jpg",
    title: "Puma Sliers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "140,00",
    newPrice: "50",
    company: "Nike",
    color: "black",
    category: "sandals",
  },
  {
    id:17,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/71fkr0JfVyL._AC_UL600_FMwebp_QL65_.jpg",
    title: "Chunky High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "140,00",
    newPrice: "50",
    company: "Vans",
    color: "black",
    category: "heels",
  },
  {
    id:18,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/51lsbkNZBwL._AC_UL600_FMwebp_QL65_.jpg",
    title: "Slip On Stiletto High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "140,00",
    newPrice: "100",
    company: "puma",
    color: "black",
    category: "heels",
  },
  {
    id:19,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/71RjwX4PumL._AC_UL600_FMwebp_QL65_.jpg",
    title: "DREAM PAIRS Court Shoes",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "140,00",
    newPrice: "150",
    company: "Nike",
    color: "red",
    category: "heels",
  },
  {
    id:20,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/71oLUSuh7vL._AC_UL600_FMwebp_QL65_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "140,00",
    newPrice: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },

  {
    id:21,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/4125IFEnW4L._AC_UL600_FMwebp_QL65_.jpg",
    title: "Low Mid Block Heels",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "140,00",
    newPrice: "200",
    company: "Nike",
    color: "black",
    category: "heels",
  },
  {
    id:22,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/51Dr7zqtUtL._AC_UL600_FMwebp_QL65_.jpg",
    title: "Nike chunky",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "heels",
  },
  {
    id:23,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/81vRwm45CZL._AC_UL600_FMwebp_QL65_.jpg",
    title: "Amore Fashion Stilettos",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "140,00",
    newPrice: "150",
    company: "Adidas",
    color: "white",
    category: "heels",
  },
  {
    id:24,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/61NnQoEPdlL._AC_UL600_FMwebp_QL65_.jpg",
    title: "Bridal Sandals Glitter",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "heels",
  },
  {
    id:25,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/71U2ZbaB-IL._AC_UL600_FMwebp_QL65_.jpg",
    title: "Wedding Prom Bridal",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "flats",
  },
  {
    id: 26,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: 'https://m.media-amazon.com/images/I/41B73xL6CBL._AC_UL600_FMwebp_QL65_.jpg',
    title: "Nike Running Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    color: "black",
    category: "sneakers",
  },
  {
    id: 27,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/51ttb1G2GAL._AC_UL600_FMwebp_QL65_.jpg",
    title: "Flat Slip On Pumps",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Vans",
    color: "green",
    category: "flats",
  },
  {
    id:28,
    dis:"  As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated.As a brand new startup, we used Mailchimp's website builder to get our story and business online quickly and easily. This intuitive builder makes trying out new ideas and adding updates straightforward and uncomplicated."
    ,
    img: "https://m.media-amazon.com/images/I/71LjpWQoo4L._AC_UL600_QL65_.jpg",
    title: "Knit Ballet Flat",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "flats",
  }
];

export default data;
